---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "inst/README-"
)
```

```{r example}
library(hashsize)

# Load the tidyverse to populate the symbol table
suppressPackageStartupMessages(library(tidyverse))

buckets <- .Call(hashsize:::hashsize_symbols, 4119L)
lens <- lengths(buckets)
total <- sum(lens)
total
summary(lens)
hist(lens)

elapsed_time <- function(expr) system.time(expr)[[3]]

time_large_bucket <- function(buckets, n, median, times = 1e8) {
  b <- buckets[lengths(buckets) >= n]
  b <- b[[sample.int(length(b), 1)]]

  front <- as.character(b[[1]])
  back <- as.character(b[[length(b)]])
  med <- as.character(b[[median]])
  list(
    bucket_length = length(b),
    front_name = front,
    front = elapsed_time(.Call(hashsize:::hashsize_lookup_bench, front, times)),
    back_name = back,
    back = elapsed_time(.Call(hashsize:::hashsize_lookup_bench, back, times)),
    med_name = med,
    med = elapsed_time(.Call(hashsize:::hashsize_lookup_bench, med, times)))
}

to_df <- function(x) {
  df <- do.call(rbind.data.frame, x)

  percent <- function(x) sprintf("%.2f%%", x * 100)

  df$total <- percent((df$back - df$front) / df$front)
  df$median <- percent((df$med - df$front) / df$front)
  df
}

knitr::kable(
  to_df(replicate(50, time_large_bucket(buckets, 10, 5, 1e6), simplify = FALSE)))
```

## Performance between current `HSIZE` and larger `HSIZE`.
<inst/script.R> has a simple benchmark, to compare between the current value
and a larger one. The benchmark looks up every symbol in the hash a certain
number of times (10,000 in this example).

```shell
R --version
# R Under development (unstable) (2017-05-16 r72682) -- "Unsuffered Consequences"

# Current HSIZE (4119)
Rscript inst/script.R 4119 $((10**4))
# [1] 15959
#    user  system elapsed
#   5.245   0.005   5.252

# HSIZE of 2^16 (65536)
Rscript inst/script.R $((2**16)) $((10**4))
# [1] 16093
#    user  system elapsed
#   4.280   0.007   4.288
```

## Hashed environment performance
An ideal hash would have constant time lookup regardless of hash size (third
column).

HSIZE = 4119
```
for i in {1..7};do Rscript inst/script2.R $((1 * 10**$i));done
# 10      0.002   2e-04
# 100     0.002   2e-05
# 1000    0.002   2e-06
# 10000   0.017   1.7e-06
# 1e+05   0.263   2.63e-06
# 1e+06   11.779  1.1779e-05
# 1e+07 canceled after running for over an hour
```

HSIZE = 2^16
```shell
for i in {1..7};do Rscript inst/script2.R $((1 * 10**$i));done
# 10      0.001   1e-04
# 100     0.001   1e-05
# 1000    0.00299999999999997     2.99999999999998e-06
# 10000   0.018   1.8e-06
# 1e+05   0.202   2.02e-06
# 1e+06   3.007   3.007e-06
# 1e+07   128.71  1.2871e-05
```
